name: ApiPlus
main: team.ApiPlus.ApiPlus
version: 1
authors: [SirTyler, Atlan1]
depend: [Spout]
softdepend: [WorldGaurd, LWC]
commands:
    loadout:
        description: API+ Loadout Command.
        aliases: [load,l+]
        usage: /loadout - Shows API+ Loadouts